// Regenerate the screen-share compatibility matrix in README.md from the
// single source of truth (site/src/data/compat.js).
//
// Run manually with `npm run gen:compat`, and automatically once per release
// via .github/workflows/update-readme-compat.yml. Uses only Node core + the
// data module (no dependencies), so it runs without `npm install`.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { compat, PLATFORM_ORDER, PLATFORM_GUARANTEE } from '../site/src/data/compat.js';

const STATUS = {
  hidden: '✅ Hidden',
  partial: '🟡 Partial',
  visible: '❌ Visible',
  untested: '⬜ Untested',
};
const GUARANTEE = { guaranteed: 'OS-guaranteed', bestEffort: 'best-effort' };

const __dirname = dirname(fileURLToPath(import.meta.url));
const README = resolve(__dirname, '../README.md');
const START = '<!-- COMPAT:START -->';
const END = '<!-- COMPAT:END -->';

const verifiers = (list) =>
  !list || list.length === 0
    ? '_Testers wanted_'
    : list.map((p) => (p.profile ? `[@${p.name}](${p.profile})` : `@${p.name}`)).join(', ');

const table = (rows) =>
  [
    '| OS version | Environment | Screen-share | Verified by | App |',
    '| --- | --- | --- | --- | --- |',
    ...rows.map(
      (r) =>
        `| ${r.version} | ${r.env} | ${STATUS[r.result] || STATUS.untested} | ${verifiers(
          r.verifiers
        )} | ${r.appVersion || '—'} |`
    ),
  ].join('\n');

const blocks = PLATFORM_ORDER.map((platform) => {
  const rows = compat.filter((r) => r.platform === platform);
  if (!rows.length) return '';
  const g = GUARANTEE[PLATFORM_GUARANTEE[platform]] || '';
  return `#### ${platform} — ${g}\n\n${table(rows)}`;
})
  .filter(Boolean)
  .join('\n\n');

const generated = `${START}
<!-- Generated by scripts/gen-compat.mjs — edit site/src/data/compat.js, then run \`npm run gen:compat\`. -->

${blocks}

${END}`;

const md = readFileSync(README, 'utf8');
const i = md.indexOf(START);
const j = md.indexOf(END);
if (i === -1 || j === -1) {
  console.error(`README.md is missing the ${START} / ${END} markers.`);
  process.exit(1);
}
writeFileSync(README, md.slice(0, i) + generated + md.slice(j + END.length));
console.log('✓ README compatibility matrix regenerated.');
